2018-12-21 06:13:41,374 ERROR: Exception on / [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/routes.py", line 29, in index
    return render_template("index.html", title='Home', form=form, user=user, posts=posts)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/base.html", line 30, in top-level template code
    {% block content %}
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/index.html", line 14, in block "content"
    {{ form.post.submit() }}
UndefinedError: 'wtforms.fields.simple.TextAreaField object' has no attribute 'submit'
2018-12-21 06:14:10,842 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:43]
2018-12-21 06:28:06,146 ERROR: Exception on / [POST] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/routes.py", line 23, in index
    post = Post(body=form.post.date, author=current_user)
AttributeError: 'TextAreaField' object has no attribute 'date'
2018-12-21 06:31:16,756 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:43]
2018-12-21 07:30:52,976 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:43]
2018-12-21 07:31:41,696 ERROR: Exception on / [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/routes.py", line 29, in index
    return render_template("index.html", title='Home', form=form, user=user, posts=posts)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/base.html", line 32, in top-level template code
    {% block content %}
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/index.html", line 21, in block "content"
    {% include('_post.html') %}
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/app/templates/_post.html", line 4, in top-level template code
    <img src="{{ user.avatar(36) }}">
UndefinedError: 'function object' has no attribute 'avatar'
2018-12-21 07:33:35,360 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:43]
2018-12-21 08:08:07,359 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:43]
2018-12-22 00:16:10,716 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:46]
2018-12-22 00:16:53,088 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:46]
2018-12-22 00:17:14,941 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:46]
2018-12-22 00:17:18,600 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:46]
2018-12-22 00:22:15,905 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:46]
2018-12-22 00:22:19,068 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:46]
