2019-01-02 15:04:31,161 ERROR: Exception on /favicon.ico [GET] [in c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2019-01-02 15:05:04,286 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-02 15:06:59,923 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-02 15:47:01,861 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-02 15:47:26,288 ERROR: Exception on /explore [GET] [in c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\routes.py", line 65, in explore
    return render_template('index.html', title='Home Page', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\index.html", line 5, in template
    <h1>{{ _(Hi, %(username)s!', username=current_user.username) }}</h1>
TemplateSyntaxError: unexpected '%'
2019-01-02 15:47:28,786 ERROR: Exception on / [GET] [in c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\routes.py", line 35, in index
    prev_url=prev_url)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\supratimdas\pycharmprojects\preprocessingpipelinempfe\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\index.html", line 5, in template
    <h1>{{ _(Hi, %(username)s!', username=current_user.username) }}</h1>
TemplateSyntaxError: unexpected '%'
2019-01-02 16:44:45,141 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-03 10:54:02,523 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-03 10:54:12,076 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-03 10:54:59,529 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-03 11:29:09,815 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
2019-01-03 12:04:53,812 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:51]
