2019-01-03 13:49:03,280 ERROR: Exception on /auth/login [GET] [in c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\auth\routes.py", line 29, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2019-01-03 13:52:56,980 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:70]
2019-01-03 13:53:01,460 ERROR: Exception on /auth/login [GET] [in c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\auth\routes.py", line 29, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\auth\login.html", line 12, in block "app_content"
    <p>{{ _('New User?') }} <a href="{{ url_for('register') }}">{{ _('Click to Register!') }}</a></p>
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2019-01-03 13:54:04,790 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:70]
2019-01-03 13:56:07,334 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:70]
2019-01-03 15:58:46,821 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:71]
2019-01-03 16:00:52,595 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:71]
